param(
    [string]$Root = "",
    [switch]$Open,
    [string]$Theme = ""
)

$ErrorActionPreference = "Stop"

function Ensure-Directory {
    param([string]$Path)
    if (-not (Test-Path $Path)) { New-Item -ItemType Directory -Force -Path $Path | Out-Null }
}

function Read-FileSafe {
    param([string]$Path)
    if (Test-Path $Path) { return (Get-Content -Path $Path -Raw) }
    return ""
}

if ([string]::IsNullOrWhiteSpace($Root)) {
    if ($PSScriptRoot) { $Root = Split-Path -Parent $PSScriptRoot } else { $Root = (Get-Location).Path }
}

$Root = [System.IO.Path]::GetFullPath($Root)
$workspace = Join-Path $Root "workspace"
$money = Join-Path $workspace "money"
$logs = Join-Path $Root "logs"
$memory = Join-Path $Root "memory"
$config = Join-Path $Root "config"
$partners = Join-Path $workspace "partners"
$digistore = Join-Path $workspace "digistore"

Ensure-Directory $workspace
Ensure-Directory $money
Ensure-Directory $logs
Ensure-Directory $partners

$today = Get-Date -Format "yyyy-MM-dd"
$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$ideaFile = Join-Path $money ("daily_money_idea_" + $today + ".txt")
$lastIdeaFile = Join-Path $money "daily_money_idea_latest.txt"
$trackerFile = Join-Path $money "opportunity_radar.csv"
$logFile = Join-Path $logs "vex_money_brain.log"

if (-not (Test-Path $trackerFile)) {
    "date_added,idea_name,stream,score,status,cost,time_to_test,first_action,kill_criteria,notes" | Set-Content -Path $trackerFile -Encoding UTF8
}

$mission = Read-FileSafe (Join-Path $memory "MONEY_MISSION.md")
$rules = Read-FileSafe (Join-Path $memory "MONEY_RULES.md")
$streams = Read-FileSafe (Join-Path $config "streams.json")
$partnerTracker = Read-FileSafe (Join-Path $partners "moneycrunch_partner_tracker.csv")
$siteAction = Read-FileSafe (Join-Path $workspace "moneycrunch_site_action.txt")
$partnerActions = Read-FileSafe (Join-Path $workspace "moneycrunch_partner_next_actions.txt")
$digistoreReply = Read-FileSafe (Join-Path $digistore "digistore_flow_reply.txt")
$localQwen = Join-Path $Root "scripts\vex_local_qwen.ps1"

$prompt = @"
You are Vex, Shahied's local money-focused OpenClaw operator.

Mission:
$mission

Rules:
$rules

Current streams/config:
$streams

MoneyCrunch site status:
$siteAction

Partner tracker/actions:
$partnerActions

Partner tracker CSV:
$partnerTracker

Digistore latest scan/flow:
$digistoreReply

Task:
Bring Shahied ONE new money-stream idea for today.
It must be researched from the available local context, practical, low-cost, legal, and testable within 24 hours.
It must not simply repeat the current obvious tasks unless there is a new angle.

Theme hint, if any:
$Theme

Output format:
DAILY MONEY IDEA
================
Idea name:
Stream:
Why this could make money:
Who pays or converts:
What we already have:
What is missing:
First 24-hour test:
Tools needed:
Estimated cost:
Time to first test:
Risks/compliance:
Kill criteria:
Score out of 100:
Decision needed from Shahied:
"@

$reply = ""
if (Test-Path $localQwen) {
    try {
        $escapedPrompt = $prompt.Replace('"','`"')
        $reply = powershell -ExecutionPolicy Bypass -File $localQwen -Root $Root -Prompt $escapedPrompt 2>&1 | Out-String
        $reply = $reply.Trim()
    }
    catch {
        $reply = "Local Vex Qwen failed: " + $_.Exception.Message
    }
}
else {
    $reply = "Local Qwen wrapper not found. Create it first with vex_local_qwen.ps1."
}

# Clean wrapper noise if present.
$lines = $reply -split "`r?`n"
$clean = @()
$started = $false
foreach ($line in $lines) {
    if ($line -match "DAILY MONEY IDEA") { $started = $true }
    if ($started) { $clean += $line }
}
if ($clean.Count -gt 0) { $reply = ($clean -join "`r`n") }

Set-Content -Path $ideaFile -Value $reply -Encoding UTF8
Set-Content -Path $lastIdeaFile -Value $reply -Encoding UTF8

# Try to extract simple fields for tracker.
$ideaName = "Daily idea " + $today
$stream = "new_money_stream"
$score = ""
$firstAction = "Review idea with Shahied"
$killCriteria = "No traction after first test"

foreach ($line in ($reply -split "`r?`n")) {
    if ($line -like "Idea name:*") { $ideaName = $line.Substring(10).Trim() }
    if ($line -like "Stream:*") { $stream = $line.Substring(7).Trim() }
    if ($line -like "Score out of 100:*") { $score = $line.Substring(17).Trim() }
    if ($line -like "First 24-hour test:*") { $firstAction = $line.Substring(19).Trim() }
    if ($line -like "Kill criteria:*") { $killCriteria = $line.Substring(14).Trim() }
}

$csvRow = [pscustomobject]@{
    date_added = $today
    idea_name = $ideaName
    stream = $stream
    score = $score
    status = "proposed"
    cost = "low_or_unknown"
    time_to_test = "24h"
    first_action = $firstAction
    kill_criteria = $killCriteria
    notes = "Generated by Vex money brain at $stamp"
}
$csvRow | Export-Csv -Path $trackerFile -Append -NoTypeInformation -Encoding UTF8

Add-Content -Path $logFile -Value ("[" + $stamp + "] Created daily money idea: " + $ideaFile) -Encoding UTF8

Write-Host "Daily money idea created:" -ForegroundColor Green
Write-Host $ideaFile
Write-Host ""
Write-Host $reply

if ($Open) { notepad $ideaFile }
